apiVersion: v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: nginx-svc
 labels:
 app: nginx
spec:
 type: NodePort
 ports:
 - port: 80
 nodePort: 30080
 selector:
 app: nginx



















---
apiversion: v1
metadata:
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx 
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
          containerPort: 80


---
apiversion: v1
type: Deployment
metadata: 
  name: nginx 
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports: 
        containerPort: 80
---
apiVersion: v1
type: Service
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  ports:
  - port: 80
  NodePort: 300080
  selector:
    app: nginx


---
apiversion: v1
kind: Deployment
metadata: 
  name: nginx
spec:
  replicas: 3
  template:
    metadata:
      labels:
        apps: nginx
    spec:
      containers:
      - name: nginx 
        image: nginx:latest
        ports:
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    apps: nginx
spec:
  type: NodePort
  ports:
    port: 80
  nodePort: 300003
  selector:
    app: nginx